---
- name: create sysctl config
  become: true
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: "{{ sysctl_file }}"
    sysctl_set: yes
    reload: yes
  with_dict: "{{ sysctl_config }}"
  when: sysctl_config is defined
  tags: sysctl
