---
- name: Modify ulimit
  become: true
  pam_limits:
    domain: '*' 
    limit_type: "{{item.limit_type}}"
    limit_item: "{{item.limit_item}}"
    value: "{{item.value}}"
  with_items: "{{ ulimits }}"
  when: ulimits is defined
  tags: ulimit
